#!/bin/bash
set -euo pipefail

# ═══════════════════════════════════════════════════════════════
# TaskFlow — EC2 Bootstrap Script (fully automated)
# Runs once on first boot via cloud-init
# Logs to /var/log/taskflow-bootstrap.log
# ═══════════════════════════════════════════════════════════════

LOG="/var/log/taskflow-bootstrap.log"
exec > >(tee -a "$LOG") 2>&1
echo "═══════════════════════════════════════════════════"
echo "TaskFlow Bootstrap — Started at $(date)"
echo "═══════════════════════════════════════════════════"

export DEBIAN_FRONTEND=noninteractive

# ── System Update ──────────────────────────────────────────────
echo "[1/10] Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq

# ── Install Docker ─────────────────────────────────────────────
echo "[2/10] Installing Docker..."
curl -fsSL https://get.docker.com | sh
usermod -aG docker ubuntu
systemctl enable docker
systemctl start docker

# ── Install Docker Compose Plugin ──────────────────────────────
echo "[3/10] Installing Docker Compose plugin..."
apt-get install -y -qq docker-compose-plugin

# ── Install AWS CLI + Certbot ──────────────────────────────────
echo "[4/10] Installing AWS CLI and Certbot..."
apt-get install -y -qq awscli certbot python3-certbot-nginx

# ── Generate Self-Signed SSL Certificate ───────────────────────
echo "[5/10] Generating self-signed SSL certificate..."
mkdir -p /etc/ssl/taskflow
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/taskflow/privkey.pem \
    -out /etc/ssl/taskflow/fullchain.pem \
    -subj "/CN=${ec2_public_ip}" \
    2>/dev/null
chmod 644 /etc/ssl/taskflow/fullchain.pem
chmod 600 /etc/ssl/taskflow/privkey.pem
echo "  Self-signed cert created for ${ec2_public_ip}"
echo "  To upgrade to Let's Encrypt later: sudo certbot certonly --webroot -w /var/www/certbot -d yourdomain.com"

# ── Clone Repository ───────────────────────────────────────────
echo "[6/10] Cloning repository from ${repo_url}..."
if [ -d /opt/taskflow ]; then
    cd /opt/taskflow && git pull
else
    git clone ${repo_url} /opt/taskflow
fi

# ── Write Production .env ──────────────────────────────────────
echo "[7/10] Writing production .env with generated secrets..."
cat > /opt/taskflow/.env << 'ENVEOF'
# ── Generated by Terraform — DO NOT EDIT MANUALLY ──────────────
DJANGO_SETTINGS_MODULE=app.settings.production
SECRET_KEY=${secret_key}
DATABASE_URL=postgres://${db_user}:${db_password}@db:5432/${db_name}
POSTGRES_DB=${db_name}
POSTGRES_USER=${db_user}
POSTGRES_PASSWORD=${db_password}
ALLOWED_HOSTS=${ec2_public_ip},localhost,127.0.0.1
CORS_ALLOWED_ORIGINS=https://${ec2_public_ip},http://${ec2_public_ip},http://localhost
VITE_API_URL=https://${ec2_public_ip}
AWS_S3_BUCKET_NAME=${s3_bucket}
AWS_REGION=${aws_region}
ENABLE_SSL_REDIRECT=true
ENVEOF

chmod 600 /opt/taskflow/.env
chown -R ubuntu:ubuntu /opt/taskflow

# ── Start Application ─────────────────────────────────────────
echo "[8/10] Starting Docker Compose (production)..."
cd /opt/taskflow
sudo -u ubuntu docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

# Wait for health endpoint
echo "[9/10] Waiting for application to become healthy..."
RETRIES=0
MAX_RETRIES=60
until curl -skf https://localhost/api/health/ > /dev/null 2>&1 || curl -sf http://localhost/api/health/ > /dev/null 2>&1; do
    RETRIES=$((RETRIES + 1))
    if [ "$RETRIES" -ge "$MAX_RETRIES" ]; then
        echo "ERROR: Health check failed after $MAX_RETRIES attempts"
        docker compose -f docker-compose.yml -f docker-compose.prod.yml logs
        break
    fi
    echo "  Health check attempt $RETRIES/$MAX_RETRIES..."
    sleep 10
done

# ── Daily Database Backup Cron ─────────────────────────────────
echo "[10/10] Setting up daily database backup cron..."
cat > /etc/cron.d/taskflow-backup << 'CRON'
0 2 * * * ubuntu cd /opt/taskflow && /opt/taskflow/scripts/backup.sh >> /var/log/taskflow-backup.log 2>&1
CRON
chmod 644 /etc/cron.d/taskflow-backup

# ── Done ───────────────────────────────────────────────────────
echo "═══════════════════════════════════════════════════"
echo "Bootstrap Complete — $(date)"
echo "App URL: https://${ec2_public_ip}"
echo "Note: Self-signed SSL certificate — browser will show a warning (expected)"
echo "═══════════════════════════════════════════════════"
